services:
  postgres:
    image: postgres:16
    container_name: pg16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwer1234
      POSTGRES_DB: product_checker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U checker_user -d product_checker"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
