apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: dev
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres-svc
  replicas: 2
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        envFrom:
          configMapRef:
            - name: CRUD-Config-Map
          secretRef:
            - name: CRUD-Secret
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: pgdata
          mountPath: pgdata:/var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      storageClassName: "Longhorn"
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 2Gi