# Generated by Django 5.2.5 on 2025-08-23 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_no', models.CharField(max_length=50, unique=True, verbose_name='เลขที่ใบตรวจสินค้า')),
                ('product_code', models.CharField(max_length=50, verbose_name='รหัสสินค้า')),
                ('smell', models.CharField(max_length=100, verbose_name='แยกกลิ่น')),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)], verbose_name='ค่า pH')),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('NOT_PASS', 'Not Pass')], max_length=8, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['inspection_no'], name='inspections_inspect_d52a70_idx'), models.Index(fields=['product_code'], name='inspections_product_936048_idx')],
            },
        ),
    ]
