# Generated by Django 5.2.5 on 2025-08-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrecord',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคา'),
        ),
        migrations.AddField(
            model_name='inspectionrecord',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อสินค้า'),
        ),
    ]
